#!/bin/bash
# Ollama Performance Environment Setup for Ubuntu/Linux
# Optimized for multi-core systems (adjust OLLAMA_NUM_THREAD based on your CPU)

set -e

echo "╔════════════════════════════════════════════════════════════╗"
echo "║     🚀 Ollama Performance Environment Setup (Ubuntu)      ║"
echo "╚════════════════════════════════════════════════════════════╝"
echo ""

# Detect number of CPU threads
CPU_THREADS=$(nproc)
echo "Detected $CPU_THREADS CPU threads"
echo ""

# Create ollama config directory
mkdir -p ~/.ollama

# Create environment configuration file
cat > ~/.ollama/env_config.sh << 'EOF'
# Ollama Performance Optimization Environment Variables
# Generated by setup_ollama_performance.sh

# CPU and Threading
export OLLAMA_NUM_PARALLEL=4              # Run 4 models concurrently
export OLLAMA_MAX_LOADED_MODELS=4         # Keep 4 models in memory
export OLLAMA_NUM_THREAD=16               # Adjust based on your CPU cores

# Memory and Queue
export OLLAMA_MAX_QUEUE=512               # Larger request queue
export OLLAMA_KEEP_ALIVE=30m              # Models stay loaded for 30 minutes

# GPU Acceleration (NVIDIA/AMD)
export OLLAMA_GPU_LAYERS=999              # Use GPU for all layers

# Performance Features
export OLLAMA_FLASH_ATTENTION=1           # Faster attention mechanism

# Network
export OLLAMA_HOST=127.0.0.1:11434        # Bind to localhost
export OLLAMA_ORIGINS=*                   # Allow all origins

# Debugging
export OLLAMA_DEBUG=0                     # Disable debug for speed
EOF

# Update thread count based on detected CPU
sed -i "s/export OLLAMA_NUM_THREAD=16/export OLLAMA_NUM_THREAD=$CPU_THREADS/" ~/.ollama/env_config.sh

echo "✅ Environment configuration created at: ~/.ollama/env_config.sh"
echo ""

# Add to shell profile if not already present
SHELL_RC=""
if [ -f ~/.bashrc ]; then
    SHELL_RC=~/.bashrc
elif [ -f ~/.zshrc ]; then
    SHELL_RC=~/.zshrc
fi

if [ -n "$SHELL_RC" ]; then
    if ! grep -q "source ~/.ollama/env_config.sh" "$SHELL_RC"; then
        echo "" >> "$SHELL_RC"
        echo "# Ollama Performance Optimization" >> "$SHELL_RC"
        echo "if [ -f ~/.ollama/env_config.sh ]; then" >> "$SHELL_RC"
        echo "    source ~/.ollama/env_config.sh" >> "$SHELL_RC"
        echo "fi" >> "$SHELL_RC"
        echo "✅ Added to $SHELL_RC"
    else
        echo "ℹ️  Already configured in $SHELL_RC"
    fi
fi

echo ""
echo "╔════════════════════════════════════════════════════════════╗"
echo "║                    ✅ Setup Complete!                      ║"
echo "╚════════════════════════════════════════════════════════════╝"
echo ""
echo "📝 Next steps:"
echo "   1. Reload your shell: source $SHELL_RC"
echo "   2. Or start a new terminal session"
echo "   3. Run: ./install_ubuntu.sh to complete installation"
echo ""
